### ISSUE TITLE
Attempt to compare nil with number protocol.lua line 310

### ISSUE THREAD

**Issue by LenweSaralonde** [tmg-pub/crossrp#2]
Occurs mostly on non RP realms (ie EU-Hyjal on Alliance side, SW Trade district)

Date: 2021-12-31 18:48:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\CrossRP\protocol.lua line 310:
   attempt to compare nil with number
Debug:
   [string "@CrossRP\protocol.lua"]:310:
      CrossRP\protocol.lua:295
   [string "@CrossRP\protocol.lua"]:1941:
      CrossRP\protocol.lua:1940
   [string "@CrossRP\protocol.lua"]:2586: OnMouseoverUnit()
   [string "@CrossRP\CrossRP.lua"]:257:
      CrossRP\CrossRP.lua:255
   [string "=[C]"]: ?
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@CrossRP\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...ce\AddOns\CrossRP\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None

**Comment by LenweSaralonde** [comment]
This is caused by the current latest version of LibRealmInfo (v17) that contains outdated realm data + some typos (ie EU `Cho'Gall` written as `Cho’gall` in LibRealmInfo with at the wrong quote character). The bug can be observed on EU-Cho'gall realm with the current version of CrossRP (2.1.8) and another add-on that includes the v17 of LibRealmInfo (is Musician v1.9.0.10)

This is definitely a LibRealmInfo bug. Unfortunately, it doesn't seem to be maintained anymore so I'm considering taking over the maintenance of LibRealmInfo and creating a PR for CrossRP to have it updated.

**Comment by tmg-pub** [comment]
I'm sure some people would appreciate if you can fix those quirks. :- )
