### ISSUE TITLE
LUA error when mouseover a character when some BNet friends from another area are logged in

### ISSUE THREAD

**Issue by LenweSaralonde** [tmg-pub/crossrp#3]
Steps:
1. Have a BNet account with friends in Area 1 (ie EU)
2. Create a trial WoW account in another Area 2 (ie US)
3. Create character on the trial account in Area 2 (ie Moonguard)
4. Wait approx 20s
5. Mouse over a character 

The following LUA error occurs:
`Interface\AddOns\CrossRP\CrossRP.lua:732: attempt to index field 'realmName' (a nil value)`

The root cause is the object returned by the `C_BattleNet.GetFriendGameAccountInfo( friend, account_index )` function is missing the `realmName` property.

Since there is no way to interact with players from other areas, we could just ignore those who `realmName` that is `nil`.

**Comment by tmg-pub** [comment]
Merged your changes. Thanks!
